apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  connection: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOnBvc3RncmVzQDE3Mi4xOS44OC4yMDU6NTQzMi9kYl9sb2NhbA==
  fernet-key: YWlyZmxvdy1ldGwta3ViZXJuZXRlcy1mZXJuZXQta2V5
  webserver-secret-key: YWlyZmxvdy1ldGwta3ViZXJuZXRlcy13ZWJzZXJ2ZXItc2VjcmV0LWtleQ==